my_tuple = ('One' , 'Two' , 'Three' , 'Four' , 'Five' , 'Six' , 'Seven')
print(my_tuple)
print("__________________________________________________________________")
my_list = list(my_tuple)
my_list.insert(1 , 'Ten')
my_list.append('Eight')
print(my_list)
print("__________________________________________________________________")
my_tuple = tuple(my_list)
print(my_tuple)
print("__________________________________________________________________")
index = my_tuple.index(my_tuple[-2])
print("index number of second last element : ",index)